### ISSUE TITLE
Support Julia v0.6

### ISSUE THREAD

**Issue by isuruf** [symengine/SymEngine.jl#61]
See failed log, http://pkg.julialang.org/logs/SymEngine_0.6.log

**Comment by jverzani** [comment]
I think most of these are minor compat issues, but the error comes from something that currently isn't working, but should be fixed. It is in how the `lambdify` function makes functions. They need compiling before usage leaving the form `lambdify(ex)(val)` throwing that error. (https://discourse.julialang.org/t/help-calling-a-function-defined-from-expressions/1340/5). A simple fix is to assign first: `fn = lambdify(ex); fn(val)` but until the underlying issue is addressed the plot recipes won't work either.
